// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using EF.Entities;
using Interfaces;

namespace EF.Entities
{
	public partial class Persons: BaseEntity, IPersons
	{
		public virtual DateTime EntryDateTine { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
				public virtual ICollection<PersonMedia> PersonMedia {get; set;}
				public virtual Persons_Doctor Persons_Doctor {get; set;}
				public virtual UserSignIn UserSignIn {get; set;}
		
			// ---------Parent Relationships
	

	}
}
