// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Collections.Generic;
using Common.DataEntites;
using GenSoft.Entities;
using GenSoft.Interfaces;

namespace GenSoft.Entities
{
	public partial class Processes: BaseEntity, IProcesses
	{
		public virtual string Description { get; set; }
		public virtual string Name { get; set; }
		public virtual int ParentProcessId { get; set; }
		public virtual string Symbol { get; set; }
		public virtual string UserId { get; set; }
		public virtual bool AutoRun { get; set; }

		//-------------------Navigation Properties -------------------------------//
			// ---------Child Relationships
		
			// ---------Parent Relationships
	

	}
}
