// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using EF.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EF.Mappings
{
	public class PersonsMap
	{
		public static void Map(EntityTypeBuilder<Persons> entityBuilder)
		{
			entityBuilder.ToTable("Persons", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.EntryDateTine).HasColumnName("EntryDateTine").IsRequired();
		//-------------------Navigation Properties -------------------------------//
				entityBuilder.HasMany(x => x.PersonMedia).WithOne(p => p.Persons).HasForeignKey(c => c.PersonId).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.Persons_Doctor).WithOne(p => p.Persons).HasForeignKey<Persons_Doctor>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
				entityBuilder.HasOne(p => p.UserSignIn).WithOne(p => p.Persons).HasForeignKey<UserSignIn>(c => c.Id).OnDelete(DeleteBehavior.Restrict);
	
				//----------------Parent Properties
	
		}
	}
}
