// <autogenerated>
//   This file was generated by T4 code generator MRManger-DBContext.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;

namespace GenSoft.DBContexts
{
	public partial class GenSoftDbContext:DbContext
	{
		public DbSet<MachineInfo> Machines { get; set; }
        public DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public DbSet<Process> Processes { get; set; }
        public DbSet<UserSignIn> Users { get; set; }
        public DbSet<ComplexEventAction> ComplextEventActions { get; set; } 


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(DBContext.Properties.Settings.Default.DbConnectionString);
		}
	
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
				
				//VisitTypeMap.Map(modelBuilder.Entity<VisitType>());
		}
	}
}
