// <autogenerated>
//   This file was generated by T4 code generator MRManger-DBContext.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.ComponentModel;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;

namespace GenSoft.DBContexts
{
	public partial class GenSoftDbContext
	{
		private static readonly GenSoftDbContext _instance = new GenSoftDbContext();

		public static GenSoftDbContext Instance => _instance;

		static GenSoftDbContext()
		{
			if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return;
			Instance.Database.EnsureDeleted();
			Instance.Database.EnsureCreated();
			// Instance.Database.Migrate();
			CreateSeedData();
		}

		private static void CreateSeedData()
		{
			using (var ctx = new GenSoftDbContext())
			{
				ctx.ApplicationSettings.Add(new ApplicationSetting() {AutoRun = true});
				ctx.Machines.Add(new MachineInfo() {MachineName = "ALPHAQUEST-PC", Processors = 8});
                ctx.Users.Add(new UserSignIn() { Password = "Test", Username = "joe" });
                ctx.SaveChanges();
                Instance.Database.ExecuteSqlCommand(@"
                	SET IDENTITY_INSERT dbo.Processes ON
                		Insert Into dbo.Processes (Id, ParentProcessId, Name, Description, Symbol, UserId) Values('1','0','Starting System','Prepare system for Intial Use','Start','System')
                		Insert Into dbo.Processes (Id, ParentProcessId, Name, Description, Symbol, UserId) Values('2','1','User SignOn','User Login','User','System')
                        Insert Into dbo.Processes (Id, ParentProcessId, Name, Description, Symbol, UserId) Values('3','2','Load User Screen','User Screen','UserScreen','joe')                		
                	SET IDENTITY_INSERT dbo.Processes OFF");

			    


			}
		}
			   
			
		
	}
}
