// <autogenerated>
//   This file was generated by T4 code generator MRManger-DBContext.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.ComponentModel;

namespace GenSoft.DBContexts
{
	public partial class GenSoftDBContext
	{
		private static readonly GenSoftDBContext _instance = new GenSoftDBContext();

		public static GenSoftDBContext Instance => _instance;

		static GenSoftDBContext()
		{
			if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return;
			Instance.Database.EnsureDeleted();
			Instance.Database.EnsureCreated();
			CreateSeedData();
		}

		private static void CreateSeedData()
		{

		}
               
			
		
	}
}
