// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class MachinesMap
	{
		public static void Map(EntityTypeBuilder<Machines> entityBuilder)
		{
			entityBuilder.ToTable("Machines", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.MachineName).HasColumnName("MachineName").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.MachineName).HasColumnName("MachineName").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Processors).HasColumnName("Processors").IsRequired();
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
	
		}
	}
}
