// <autogenerated>
//   This file was generated by T4 code generator MRManger-DataEntities.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using GenSoft.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GenSoft.Mappings
{
	public class UsersMap
	{
		public static void Map(EntityTypeBuilder<Users> entityBuilder)
		{
			entityBuilder.ToTable("Users", "dbo");
			entityBuilder.HasKey(t => t.Id);
			entityBuilder.Property(t => t.Id).HasColumnName("Id").UseSqlServerIdentityColumn();	
			entityBuilder.Property(t => t.Password).HasColumnName("Password").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Username).HasColumnName("Username").IsRequired().HasMaxLength(Int32.MaxValue);
			entityBuilder.Property(t => t.Username).HasColumnName("Username").IsRequired().HasMaxLength(Int32.MaxValue);
		//-------------------Navigation Properties -------------------------------//
	
				//----------------Parent Properties
	
		}
	}
}
