// <autogenerated>
//   This file was generated by T4 code generator MRManger-DBContext.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System.ComponentModel;

namespace GenSoft.DBContexts
{
	public partial class GenProDBContext
	{
		private static readonly GenProDBContext _instance = new GenProDBContext();

		public static GenProDBContext Instance => _instance;

		static GenProDBContext()
		{
			if (System.ComponentModel.LicenseManager.UsageMode == LicenseUsageMode.Designtime) return;
			Instance.Database.EnsureDeleted();
			Instance.Database.EnsureCreated();
			CreateSeedData();
		}

		private static void CreateSeedData()
		{
			//No test data for EntityAttributes
			//No test data for MediaTypes
			//No test data for MedicalCategory
			//No test data for MedicalSystems
			//No test data for Patients
			//No test data for Persons
			//No test data for Phase
			//No test data for SyntomPriority
			//No test data for Syntoms
			//No test data for SyntomStatus
			//No test data for VisitType
			//No test data for Interviews
			//No test data for Questions
			//No test data for ResponseOptions
			//No test data for Media
			//No test data for DefaultImages
			//No test data for PersonMedia
			//No test data for MedicalSystemInterviews
			//No test data for SyntomMedicalSystems
			//No test data for Persons_Doctor
			//No test data for PatientVisit
			//No test data for PatientSyntoms
			//No test data for PatientResponses
			//No test data for Response
			//No test data for ResponseImages
			//No test data for UserSignIn
		}
               
			
		
	}
}
